### ISSUE TITLE
faite le devoire

### ISSUE THREAD

**Issue by ghost** [Monocure/Devoir.Deezer#1]
dizeur,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

**Comment by Monocure** [comment]
Onze Heures...

**Comment by ghost** [comment]
vous ete l'owneur!!!

**Comment by ghost** [comment]
vous ete l'owneur!!!

**Comment by ghost** [comment]
vous ete l'owneur!!!

**Comment by ghost** [comment]
vous ete l'owneur!!!

**Comment by ghost** [comment]
vous ete l'owneur!!!

**Comment by ghost** [comment]
vous ete l'owneur!!!
